name: Test
on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Test
        run: dotnet test tests/Oxide.Tests --logger "trx;LogFileName=TestResults-Oxide.Tests.trx"

      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: TestResults-Oxide.Tests
          path: ${{ github.workspace }}/tests/Oxide.Tests/TestResults/TestResults-Oxide.Tests.trx

